---
title: "README"
author: "Anka van de Merbel"
date: "2023-12-06"
output:
  html_document: 
   toc: true
   toc_depth: 4
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Statistical Matching using the Instrumental Variable Assumption

## 1. Introduction
The purpose of this project is to evaluate the use of an instrumental variable assumption when statistically matching two data sets. Within this project the focus lies on categorical variables with two categories each, which is the premise the functions outlined below are based on. In section 2 each functions purpose is described. The input arguments and their formats are given and the output is outlined. Section 3 includes descriptions of the various scripts used and what you can find in them. In section 4 the Data folder is explained. 

## 2. Functions
### a. Generating data
#### *GeneratePopulation_InstrumentalVariable*

<br>

This function generates a population distribution under the instrumental variable assumption (conditional independence of the instrumental variable and the outcome, given the mediator). 

<br>
<br>

**REQUIRED PACKAGES**: dplyr, sampling

**REQUIRED FUNCTIONS**: Reverse_OddsRatio

<br>
<br>

INPUT													| description
------------------------------|---------------------------------------------------------------------------------------------
N 								= 1000000		| Numeric argument indicating the size of the population to be generated
p_instrumental 		= runif(1)	| Numeric argument indicating the distribution of the instrumental variable in the population
p_mediator 				= runif(1)	| Numeric argument indicating the distribution of the mediating variable in the population
p_outcome 				= runif(1)	| Numeric argument indicating the distribution of the outcome variable in the population
oddsratio_ins_med = 7					| Odds Ratio between the instrumental and the mediating variable in the population
oddsratio_med_out = 4					| Odds Ratio between the mediating and the outcome variable in the population


OUTPUT												| description
------------------------------|---------------------------------------------------------------------------------------------
FullPopulation								| Data frame with the distribution of all combinations of the three variables in the population in probability and counts
DistributionMediator1					| Data frame with the distribution of the instrumental and outcome variables in the population, for level 1 of the mediator
DistributionMediator2					| Data frame with the distribution of the instrumental and outcome variables in the population, for level 2 of the mediator
AggregatedDistribution				| List of data frames with the distribution of the combination of two variables, for each statistical matching situation

<br>
<br>

#### *GeneratePopulation_NotInstrumentalVariable*

<br>

This function generates a population distribution where the instrumental variable assumption does not hold (conditional independence of the instrumental variable and the outcome, given the mediator).

<br>
<br>

**REQUIRED PACKAGES**: dplyr

**REQUIRED FUNCTIONS**: Reverse_OddsRatio

<br>
<br>

INPUT													| description
------------------------------|---------------------------------------------------------------------------------------------
mediator_1										| Data frame with the distribution of the instrumental and outcome variables in the population, for level 1 of the mediator (output from GeneratePopulation_InstrumentalVariable)
mediator_2										| Data frame with the distribution of the instrumental and outcome variables in the population, for level 2 of the mediator (output from GeneratePopulation_InstrumentalVariable)
oddsratio_mediator_1 = 1			| Odds Ratio between the instrumental and the outcome variable for level 1 of the mediator
oddsratio_mediator_2 = 1			| Odds Ratio between the instrumental and the outcome variable for level 2 of the mediator


OUTPUT												| description
------------------------------|--------------------------------------------------------------------------------------------
FullPopulation								| Data frame with the distribution of all combinations of the three variables in the population in probability and counts
DistributionMediator1					| Data frame with the distribution of the instrumental and outcome variables in the population, for level 1 of the mediator
DistributionMediator2					| Data frame with the distribution of the instrumental and outcome variables in the population, for level 2 of the mediator
AggregatedDistribution				| List of data frames with the distribution of the combination of two variables, for each statistical matching situation

<br>
<br>

#### *GenerateSample*

<br>

This function generates a sample from the population generated using the GeneratePopulation_... functions.

<br>
<br>

**REQUIRED PACKAGES**: dplyr, extraDistr

<br>
<br>

INPUT													| description
------------------------------|--------------------------------------------------------------------------------------------
population										| Data frame with the distribution of the instrumental and outcome variables in the population, (output from GeneratePopulation_InstrumentalVariable)
common_variable								| String argument which specifies which variable is jointly observed (instrumental, mediator, outcome). 
n1 = 2000 										| Numeric argument indicating the desired sample size for the first sample
n2 = 2000											| Numeric argument indicating the desired sample size for the second sample


OUTPUT												| description
------------------------------|---------------------------------------------------------------------------------------------
FirstSample										| Data frame with the counts and proportions of for each category combination in the first sample
N1														| Realized sample size for the first sample
DistributionFirstSample				| xtabs object representing the contingency table between the variables in the first sample
SecondSample									| Data frame with the counts and proportions of for each category combination in the second sample
N2														| Realized sample size for the second sample
DistributionSecondSample			| xtabs object representing the contingency table between the variables in the second sample
FirstSampleUnobserved					| Data frame with the counts and proportions of each category combination in the first sample including the 'unobserved' variable
SecondSampleUnobserved				| Data frame with the counts and proportions of each category combination in the second sample including the 'unobserved' variable
CommonVariable								| String indicating which variable was the common variable in generating the sample

<br>
<br>

### b. Statistical Matching
#### *EstimateDistribution_InstrumentalVariable*

<br>

This function estimates the distribution between the not commonly observed variables under the instrumental variable assumption. Under the instrumental variable assumption it holds that:

$$ P(Outcome = k | Instrumental = i) = \sum_j P(Mediator = j | Instrumental = i)P(Outcome = k | Mediator = j) $$

Each time one variable is commonly observed, since we have three variables this can be either the instrumental, the mediator, or the outcome. If the mediating variable is commonly observed, the equation is easily calculated. If any of the other variables is commonly observed, linear equations have to be solved to get to the final solution.
To calculate the joint probability of the not commonly observed variables, we multiply the conditional probability by the total probability. To get the most accurate result we use the total probability of the commonly observed variable, since we have the most data on this variable (from both samples). For example if we want the joint distribution of the outcome and the instrumental variables we would have:

$$ P(Outcome, Instrumental) = \sum_j P(Outcome | Mediator = j)P(Instrumental | Mediator = j)P(Mediator = j) $$

The output includes restricted probabilities and counts. In some situations it might occur that the estimation includes probabilities that are outside of the bounds of 0 and 1. This is obviously impossible so the probabilities are coerced to be between 0 and 1. 

<br>
<br>

**REQUIRED PACKAGES**: _none_

<br>
<br>

INPUT													| description
------------------------------|--------------------------------------------------------------------------------------------
sample_input									| List with the output from GenerateSample
instrumental = "instrumental"	| String variable which indicates which variable has the role of the instrumental (if other variable names are used)
mediator = "mediator"					| String variable which indicates which variable has the role of the mediator (if other variable names are used)
outcome = "outcome"						| String variable which indicates which variable has the role of the outcome (if other variable names are used)

OUTPUT												| description
------------------------------|---------------------------------------------------------------------------------------------
Estimation										| Data frame with the estimated (restricted) probabilities and (restricted) counts of each variable combination of the not commonly observed variables

<br>
<br>

#### *EstimateDistribution_ConditionalIndependence*

<br>

This function estimates the distribution between the not commonly observed variables under the conditional independence assumption. Under the instrumental variable assumption it holds that:

$$ P(Z,Y) = \sum_x P(Z | X = x)P(Y | X = x)P(X = x) $$

The conditional independence assumption assumes that whatever the situation is, the not commonly observed variables are independent of each other given the commonly observed variable. In that sense there is always one situation possible and the values can be filled in in the formula.

The output includes restricted probabilities and counts. In some situations it might occur that the estimation includes probabilities that are outside of the bounds of 0 and 1. This is obviously impossible so the probabilities are coerced to be between 0 and 1. 

<br>
<br>

**REQUIRED PACKAGES**: dplyr, tools, stats, sampling

<br>
<br>

INPUT													| description
------------------------------|--------------------------------------------------------------------------------------------
sample_input									| List with the output from GenerateSample


OUTPUT												| description
------------------------------|---------------------------------------------------------------------------------------------
Estimation										| Data frame with the estimated (restricted) probabilities and (restricted) counts of each variable combination of the not commonly observed variables

<br>
<br>

### c. Bootstrap
#### *StatisticalMatching_Bootstrap*

<br>

This function takes a bootstrap sample from the input and estimates the joint distribution of not commonly observed variables. 

<br>
<br>

**REQUIRED PACKAGES**: _none_

**REQUIRED FUNCTIONS**: EstimateDistribution_InstrumentalVariable, EstimateDistribution_ConditionalIndependence

<br>
<br>

INPUT													| description
------------------------------|--------------------------------------------------------------------------------------------
sample_input									| Data frame with two samples, with one overlapping variable (output of GenerateSample)
assumption = c("IVA", "CIA")  | String variable indicating under which assumption the estimation is done; instrumental variable or conditional independence
restriction = FALSE           | Boolean indicating whether the probabilities in the estimation need to be restricted between 0 and 1


OUTPUT												| description
------------------------------|---------------------------------------------------------------------------------------------
estimated  										| Numeric vector with the bootstrapped estimation of the joint distribution of the not commonly observed variables
variable_combinations         | Data frame with the category combinations in the same order as the estimated values (for reference)

<br>
<br>

#### *StatisticalMatching_BootstrapParameters*

<br>

This function estimates the mean, median, variance and standard deviation of the bootstrap estimations calculated using StatisticalMatching_Bootstrap. These parameters are calculated for each category combination separately. Below an example for three bootstrap samples:

variable X | variable Y | Bootstrap 1 | Bootstrap 2 | Bootstrap 3 | mean | median | variance | standard deviation
-----------|------------|-------------|-------------|-------------|------|--------|----------|--------------------
1          | 1          | .3          | .25         | .31         | .287 | .3     | .001     | .0321
1          | 2          | .03         | .04         | .04         | .037 | .04    | < .0001  | .0058
2          | 1          | .09         | .11         | .07         | .09  | .09    | < .0001  | .02
2          | 2          | .58         | .60         | .58         | .587 | .58    | .0001    | .012

<br>
<br>

**REQUIRED PACKAGES**: _none_

**REQUIRED FUNCTIONS**: GenerateSample, EstimateDistribution_InstrumentalVariable, EstimateDistribution_ConditionalIndependece 

<br>
<br>

INPUT													| description
------------------------------|--------------------------------------------------------------------------------------------
bootstraps  									| Data frame with the bootstrapped estimations of the joint distribution (output of StatisticalMatching_Bootstrap
variable_combinations         | Data frame with the variable combinations used in estimating the bootstraps (output of StatisticalMatching_Bootstrap)


OUTPUT												| description
------------------------------|---------------------------------------------------------------------------------------------
result    										| List with a data frame for each statistical matching situation with the category combinations and their mean, variance. standard deviation, bias and RMSE

<br>
<br>

#### *StatisticalMatching_FullBootstrap*

<br>

This function uses the above bootstrap functions to perform the bootstrap analyses and give output. 

<br>
<br>

**REQUIRED PACKAGES**: _none_

**REQUIRED FUNCTIONS**: StatisticalMatching_Bootstrap, StatisticalMatching_BootstrapParameters, Check_Order 

<br>
<br>


INPUT		                  	| description
------------------------------|--------------------------------------------------------------------------------------------
B  									| Numeric indicating how many bootstrap samples should be taken
sample_input                  | Output from GenerateSample to bootstrap from
assumption = c("IVA", "CIA")  | String indicating which method to use for estimation
restriction = FALSE           | Boolean indicating whether to use restricted or unrestricted probabilities


OUTPUT								| description
------------------------------|---------------------------------------------------------------------------------------------
bootstrap_parameters				| list with a dataframe for each statistical matching situation with the category combinations and their mean, variance, standard deviation, bias and RMSE


<br>
<br>

### d. Simulation
#### *StatisticalMatching_Simulation*

<br>

This function estimates the joint distribution from a sample simulated form the population. 

<br>
<br>

**REQUIRED PACKAGES**: _none_

**REQUIRED FUNCTIONS**: GenerateSample, EstimateDistribution_InstrumentalVariable, EstimateDistribution_ConditionalIndependece 

<br>
<br>

INPUT													| description
------------------------------|--------------------------------------------------------------------------------------------
population  									| Data frame with the population you want to simulate from (output FullPopulation from GeneratePopulation_...)
assumption  = c("IVA", "CIA") | String variable indicating under which assumption to estimate the joint probability, instrumental variable or conditional independence
restriction = FALSE           | Boolean indicating whether to restrict the probabilities between 0 and 1
situations  = c("instrumental", "mediator", "outcome") | String variable indicating for which situation you want to simulate, common instrumental, mediator or outcome (all by default)
n1          = 2000            | Numeric variable indicating the desired sample size of the first sample
n2          = 2000            | Numeric variable indicating the desired sample size of the second sample


OUTPUT												| description
------------------------------|---------------------------------------------------------------------------------------------
estimated  										| List of numeric vectors for each situation containing the estimated joint probabilities for all variable combinations
variable_combinations         | List of the variable combinations in the order of the estimated probabilities (for reference)

<br>
<br>

#### *StatisticalMatching_TrueParameters*

<br>

This function calculates from simulated estimations the estimated 'true' mean, variance and standard deviation. This is done in the same way as in the Bootstrap functions, for each category combination. 

<br>
<br>

**REQUIRED PACKAGES**: _none_

<br>
<br>

INPUT													| description
------------------------------|--------------------------------------------------------------------------------------------
simulations  									| Data frame with the estimated joint probabilities from a simulation (output from StatisticalMatching_Simulation)
variable_combinations         | List of the variable combinations in the order of the estimated probabilities in the simulatins (output from StatisticalMatching_Simulation)

OUTPUT												| description
------------------------------|---------------------------------------------------------------------------------------------
result    										| List of data frames for each situation containing the 'true' mean, median, variance and standard deviation for each category combination

<br>
<br>

#### *StatisticalMatching_EstimationError*

<br>

This function calculates the _absolute_ difference and the _squared_ difference between each simulated distribution and the population distribution, for each category combination. It then returns (for each situation and each category combination) four statistics:

- The Mean Absolute Error (MAE): With $s$ the number of simulated distributions $\hat{y}, ( \hat{y_i}, i = 1, 2, ..., s)$ and $y$ the distribution in the population it is defined as

$$ MAE = \frac{1}{s} \sum^{s}_{i=1} | \hat{y_i} - y| $$
  
- The Mean Squared Error (MSE): With $s$ the number of simulated distributions $\hat{y}, ( \hat{y_i}, i = 1, 2, ..., s)$ and $y$ the distribution in the population it is defined as

$$ MSE = \frac{1}{s} \sum^{s}_{i=1} (\hat{y_i} - y)^2 $$

- The Root Mean Squared Error (RMSE):

$$ RMSE = \sqrt{MSE} $$
- The bias:
$$ Bias = \frac{1}{s} \sum^{s}_{i=1} \hat{y_i} - y $$
   
   <br>
   <br>
   
   **REQUIRED PACKAGES** = _none_

   **REQUIRED FUNCTIONS** = Check_Order
   
   <br>
   <br>
   
INPUT													| description
------------------------------|--------------------------------------------------------------------------------------------
simulations  									| Data frame with the estimated joint probabilities from a simulation (output from StatisticalMatching_Simulation)
variable_combinations         | List of the variable combinations in the order of the estimated probabilities in the simulatins (output from StatisticalMatching_Simulation)
population_distribution       | List of matrices representing the distribution of the not commonly observed variables in the population (output AggregatedDistribution from GeneratePopulation_...)

OUTPUT												| description
------------------------------|---------------------------------------------------------------------------------------------
result    										| List of data frames for each situation containing the bias, MAE, MSE and RMSE for each category combination


<br>
<br>

#### *StatisticalMatching_FullSimulation*

<br>

This function does the full simulation, from taking simulated samples to outputting the estimates.

<br>
<br>

**REQUIRED PACKAGES** = _none_

**REQUIRED FUNCTIONS** = StatisticalMatching_Simulation, StatisticalMatching_EstimationError, StatisticalMatching_TrueParameters

<br>
<br>

INPUT												                 	| description
---------------------------------------------------------|------------------------------------------------------------------
M = 500  									                     | Numeric, indicating how many simulations to do
assumption = "IVA"                                       | String indicating which estimation method to use
restriction = FALSE                                      | Boolean indicating whether to restrict the probabilities
bootstraps = FALSE                                       | Boolean indicating whether to save simulated samples for bootstrapping
nr.bootstraps = 10                                       | Numeric indicating how many samples to save for bootstrapping
n1 = 2000                                                | Numeric, indicating sample size of sample 1
n2 = 2000                                                | Numeric, indicating sample size of sample 2
situations = c("instrumental", "mediator", "outcome")    | String, indicating the different statistical matching scenarios

OUTPUT												| description
------------------------------|---------------------------------------------------------------------------------------------
SamplesBootstrap              | list containing the samples saved for bootstrapping (if TRUE)
EstimationError               | output of StatisticalMatching_EstimationError
TrueParameters                | output of StatisticalMatching_TrueParameters

<br>
<br>

### e. Support functions
#### *Reverse_OddsRatio*

<br>

This function calculates the joint distribution for a given odds ratio. The odds ratio is calculated as $\frac{ad}{bc}$ where:

x \ y     | 1   | 2   | totals
----------|-----|-----|-----------
1         | a   | b   | $rowtotal_1$
2         | c   | d   | $rowtotal_2$
totals    | $columntotal_1$ | $columntotal_2$ | total

With the row and column totals (marginals) known it is possible to rewrite the equation and solve for e.g. $a$:

$$Odds Ratio = \frac{a * (rowtotal_2 - (columntotal_1 - a))}{(rowtotal_1 - a) * (columntotal_1 -a)}$$

Then we can use the value we found to calculate $b$, $c$, and $d$ and the row and column totals.

<br>
<br>

**REQUIRED PACKAGES**: stats

<br>
<br>

INPUT													| description
------------------------------|--------------------------------------------------------------------------------------------
rowmarginals  					   | Numeric vector of row marginals (ordered by category, so say you have categories 0 and 1, the first element in the vector should be for 0)
columnmarginals         | Numeric vector of column marginals (ordered by category, so say you have categories 0 and 1, the first element in the vector should be for 0)
oddsratio       | Numeric argument indicating the desired odds ratio

OUTPUT												| description
------------------------------|---------------------------------------------------------------------------------------------
output    										| Matrix with the frequency table beloning to the given odds ratio (so the values for a, b, c, and d)

<br>
<br>


#### *Check_Order*

<br>

This function checks whether the order of the distributions in the aggregated population is the same as the order of the estimated distributions. If not it changes the order so they match and returns the newly ordered aggregate. 

<br>
<br>

**REQUIRED PACKAGES**: _none_

<br>
<br>

INPUT													| description
------------------------------|--------------------------------------------------------------------------------------------
population_distribution  					   | List of dataframes containing the joint distribution of the "unobserved" variables for each statistical matching situation
variable_combinations         | List of dataframes containing the order of the variable combinations used by either the bootstrap or the simulation function


OUTPUT												| description
------------------------------|---------------------------------------------------------------------------------------------
new_aggregate    										| List of dataframes containing population_distribution in the order of variable_combinations


#### *Checks_Output*

<br>

This file contains two functions that calculates and extracts some characteristics from the outputs of GeneratePopulation_... and GenerateSample. This way some checks can be performed such as checking whether the odds ratio procedure worked or checking what the actual distribution within the samples was. 

<br>
<br>

**REQUIRED PACKAGES**: _none_

<br>
<br>

## 3. Scripts
### a. Frechetbounds

<br>

This folder contains seven script files. The file *handcalculate_estimations_outsideFrechet* includes some hand calculated conditional probabilities to check whether it makes sense that some estimations fall outside the Fréchet bounds. In the file *marginalFrechet* marginal Fréchet bounds are calculates for each population. Finally, there are five scripts, *populationX_conditionalFrechet*, one for each population. In these scripts the conditional Fréchet bounds are calculated for each category combination.

<br>

### b. Simulations

<br>

This folder contains nine files. Four of these files, named *simulations_method_restriction*, contain the script that does the simulations for each population. Two files use the IVA and two files use the CIA method, for each method there is a version with restricted and unrestricted probabilities. Each of these files is accompanied by a *results_method_restriction* file where the results are extracted from the simulations to put into result tables. The last file is *determine_M* which is a script with an example population where several simulations are ran with an increasing number of M simulated samples. This script was used to determine how many simulations would be enough and is used to construct Figure B.1. 

<br>

### c. Bootstraps

<br>

This folder contains nine files. Four of these files, named *bootstraps_method_restriction*, contain the script that does the bootstrap analyses for each population using the samples from the simulations. Two files use the IVA and two files use the CIA method, for each method there is a version with restricted and unrestricted probabilities. Each of these files is accompanied by a *results_bootstraps_method_restriction* file where the results are extracted from the bootstraps to put into result tables. The last file is *determine_B* which is a script with an example population where several bootstraps are ran with an increasing number of B bootstrap samples. This script was used to determine how many bootstraps would be enough and is used to construct Figure B.2. 

<br>

### d. Plots

This folder contains five scripts. In *Plot_BiasFrechet_main* figure 4.1 is constructed which displays the quality estimates of the simulation study for the IVA only. In *Plot_ConfIntFrechet_main* figure 4.2 is construced which siplays the point estimates of the simulation study for both the IVA and the CIA methods. In *Plot_BiasRMSEStDev_main* figures 4.3 and 4.4 are constructed which compare the quality estimates of the IVA and the bootstrap and the quality estimates of the IVA and the CIA, respectively. In *determineM_plot* and *determineB_plot* figures B.1 and B.2 are constructed which show the bias development for different M and B respectively. These figures serve as a justification for the number of M simulations and B bootstrap samples chosen. 

### e. Tables

<br>

This folder contains one file, *Tables*, with a script constructing Tables C.1 and C.2.

<br>

### f. populations

<br>

This script includes the code used to generate the various populations. First the populations are generated where there is no violation of the IVA. The populations that need a violation of the IVA are then adjusted (using GeneratePopulation_NotInstrumentalVariable) to get a violation. 

<br>

### g. violationCIA

<br>

In this script the odds ratio between the non-overlapping given the overlapping variables is determined for each of the populations. This way it is possible to quantify to what degree the CIA is violated when there are different violations of the IVA. Under the CIA the odds ratio between the non-overlapping variables Z and Y, given overlapping variable X should be 1. 

<br>

## 4. Data
### a. Populations

<br>

This folder contains one RData file, *main_populations*, where the five populations are stored. These populations were constructed using the *populations* script. 

<br>

### b. SimulatedData

<br>

This folder contains four subfolders, one for each method and restriction combination. Within these folders are the results of the *simulations_method_restriction* scripts. Within each folder there are five files *simulate_populationX_method_restriction* so there is one file for each population. All of these files are RData files. 

<br>

### c. BootstrapData

<br>

This folder contains four subfolders, one for each method and restriction combination. Within these folders are the results of the *bootstraps_method_restriction* scripts. Within each folder there are five files *bootstraps_popX_method_restriction* so there is one file for each population. All of these files are RData files.

<br>

### d. DetermineM

<br>

This folder contains nine RData files, *resx*, where x denotes the number of M simulations. Each file contains the result of *determine_M* for one of the M simulations performed. 

<br>

### e. DetermineB

<br>

This folder contains seven RData files, *bootstraps_x*, where x denotes the number of B bootstrap samples taken. Each file contains the result of *determine_B* for one of the B bootstrap samples. 

<br>

### f. PlotData_Estimates and PlotData_Simulation

<br>

These RData files include all results. *PlotData_Estimates* includes all point estimates like mean, standard deviation etc. *PlotData_Simulation* includes all quality estimates like the bias and RMSE. These files are used for plotting and constructing the tables for in the manuscript. Over the course of the thesis project the results were added to these files, but no record of that exists (sadly). 